# Generated by Django 5.2.14 on 2026-05-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('sinopsis', models.TextField()),
                ('duracion_minutos', models.IntegerField()),
            ],
            options={
                'ordering': ['-anio'],
            },
        ),
    ]
